### ISSUE TITLE
When selecting an existing annotation, deselect the previously selected ones

### ISSUE THREAD

**Issue by robindemourat** [medialab/tesselle#26]
The app theoretically allows multiple selections (for future possible feature of selecting several annotations to delete them).

Right now selecting an annotation should deselect previously selected ones.

An example of UX context explaining this need:

How to reproduce:

* create several annotations with different comments
* switch to minified mode
* select annotation A
* select annotation B

What is happening : the input still features the text of annotation A

What we want : deselect annotation A and selection annotation B only, so that its text is the one edited in the input.

**Comment by arnaudmolo** [comment]
https://github.com/medialab/Tesselle/pull/51/commits/168e4647cbbc9fd905e3d89fbcb735867a8ba325 #51
