### ISSUE TITLE
Viewer feature

### ISSUE THREAD

**Issue by robindemourat** [medialab/tesselle#29]
The player viewer should have a route allowing to provide a data URL for fetching JSON data and image tiles of a project.

This would be the "publication" route of the app.

Possible URL pattern (to discuss) : `root/viewer?dataUrl=dataset_base_url`

Which would give in production something like : `https://medialab.github.io/glisseMontre/viewer?dataURL=my-dataset.netlify.com`

... with a JSON file at `my-dataset.netlify.com/slideshow.json` and a tiles folder at `my-dataset.netlify.com/tiles`

Relates to #27

**Comment by arnaudmolo** [comment]
#36
