### ISSUE TITLE
Player : switching to "minified" mode when no annotation is selected after first minification creates a bug

### ISSUE THREAD

**Issue by robindemourat** [medialab/tesselle#32]
How to reproduce :

1. create several annotations
1. go to preview mode
1. click on "play"
1. exit the play mode
1. deselect first annotation
1. click on "play" again

... this peculiar sequence results in the app crashing

**Comment by arnaudmolo** [comment]
https://github.com/medialab/Tesselle/pull/49/commits/afea116e0b8b0c237283837673458b6dd8417de2 #49

**Comment by arnaudmolo** [comment]
Can't reproduce

**Comment by arnaudmolo** [comment]
Ha oui j'ai trouvé et fixé ce bug avec les annotations
