### ISSUE TITLE
Free comment

### ISSUE THREAD

**Issue by robindemourat** [medialab/tesselle#34]
After our case studies meeting, we have decided to add a new feature allowing to provide ways to create annotations non related to target shapes in the editor. Targeted use cases are :

* provide a general introduction to an image storytelling
* provide a conclusion to an image storytelling
* add intermediary comments inbetween annotations when browsing a slideshow in storytelling mode

This means making the following changes :

- [x] update model to add annotations not related to shapes to a slideshow
- [x] add a "add free comment" button in the list of the aside column in editor mode
- [x] in the aside column of the editor mode, differenciate visually form-attached annotations and free annotations
- [x] in the aside column of the viewer mode, differenciate visually form-attached annotations and free annotations

**Comment by arnaudmolo** [comment]
Il faudrais que l'on se voit pour le fonctionnement a la lecture

**Comment by arnaudmolo** [comment]
Il faudrais que l'on se voit pour le fonctionnement a la lecture
