### ISSUE TITLE
[discussion] handled image file formats

### ISSUE THREAD

**Issue by robindemourat** [medialab/tesselle#38]
The tool should handle most used file formats : jpe?g, png.

Question : is it possible and wishable to handle following file formats :

* svg
* gif
* tiff
* exif

**Comment by arnaudmolo** [comment]
Voici un tableau des formats d'images supportés par les [navigateurs](https://en.wikipedia.org/wiki/Comparison_of_web_browsers#Image_format_support)

dans https://github.com/medialab/Tesselle/commit/ecb92d593d962f95c900bc0214cdd107a605af40#diff-3dffbbe345744877a45540fd93b0c122R44 j'ai permis l'upload des formats `image/svg+xml`, `image/jpeg`, `image/png`, `image/bmp`, `image/webp`

**Comment by robindemourat** [comment]
Pour mémo de notre point `jpe?g`, `png`, `bmp` et `webp` sont OK.
Il reste à adapter le code pour le `svg` (en l'état il n'aime pas) puis on sera bon là-dessus.
