### ISSUE TITLE
Some images loading will make the tiling process crash

### ISSUE THREAD

**Issue by robindemourat** [medialab/tesselle#68]
Example of this image :

<img width="1280" alt="Capture d’écran 2019-07-11 à 09 38 40" src="https://user-images.githubusercontent.com/1876890/61300838-054f2b00-a7e3-11e9-808f-94c6cb74889c.png">

When trying to upload it, the progress bar stops halfway, and the stack indicates:

```
DOMException: "Index or size is negative or greater than the allowed amount" 
The above error occurred in task _callee
```

Then, when reloading the page, the lower level of zoom displays no image:

<img width="1280" alt="Capture d’écran 2019-07-16 à 16 03 06" src="https://user-images.githubusercontent.com/1876890/61300945-40515e80-a7e3-11e9-89ef-d537afdd6cb6.png">

**Comment by robindemourat** [comment]
Other images with issues (with a great selection of images):

![EAVNBXWWsAAHdKA](https://user-images.githubusercontent.com/1876890/62304232-e0fb7b80-b47d-11e9-818c-82d01621b83a.jpg)

![D-xKaf-XUAYL6bS jpg large](https://user-images.githubusercontent.com/1876890/62304270-eeb10100-b47d-11e9-92ac-6b1469c47b3e.jpg)

**Comment by arnaudmolo** [comment]
Une version sans optimisation du temps de l'ouverture du viewer a été mise en ligne pour que tout ceci fonctionne bien maintenant que les cours ont commencés

**Comment by arnaudmolo** [comment]
cf https://github.com/medialab/tesselle/commit/9b7f5975f07bca46e2965abcce483ee42371566c
